.version: &version "15.4.1-dev.tplaceholder-19"

apiVersion: v2
name: teleport-plugin-slack
description: A Helm chart for the Teleport Slack Plugin
type: application
version: *version
appVersion: *version
