.version: &version "16.4.12-cloud-1-region-fix"

apiVersion: v2
name: teleport-plugin-discord
description: A Helm chart for the Teleport Discord Plugin
type: application
version: *version
appVersion: *version
