.version: &version "16.4.10-dev.gus-pkg-metadata.1"

apiVersion: v2
name: teleport-plugin-discord
description: A Helm chart for the Teleport Discord Plugin
type: application
version: *version
appVersion: *version
