.version: &version "17.0.0-alpha.3.gus-s3-sync-fix.1"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
