.version: &version "15.4.1-dev.tplaceholder-15"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
