.version: &version "15.4.18-dev.gus-smoke"

apiVersion: v2
name: teleport-plugin-event-handler
description: A Helm chart for Teleport Event Handler Plugin
type: application
version: *version
appVersion: *version
