.version: &version "15.4.12-fred.v15-fix-5"

name: teleport-operator
apiVersion: v2
version: *version
appVersion: *version
description: Teleport Operator provides management of select Teleport resources.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
  - Teleport
