.version: &version "15.4.0-dev.tplaceholder-7"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
