.version: &version "16.2.0-dev.datadog-plugin.1"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
