.version: &version "17.0.0-dev.gus-v17-mac-fix.3"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
