.version: &version "15.4.10-dev.capnspacehook.44579.1"

apiVersion: v2
name: teleport-plugin-jira
description: A Helm chart for the Teleport Jira Plugin
type: application
version: *version
appVersion: *version
