.version: &version "16.1.8-dev-app-servers"

name: teleport-kube-agent
apiVersion: v2
version: *version
appVersion: *version
description: Teleport provides a secure SSH, Kubernetes, database and application remote access solution that doesn't get in the way.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
  - Teleport
