.version: &version "17.0.0-dev.macos11.3"

apiVersion: v2
name: teleport-plugin-pagerduty
description: A Helm chart for the Teleport Pagerduty Plugin
type: application
version: *version
appVersion: *version
