.version: &version "15.4.12-fred.v15-fix-5"

apiVersion: v2
name: teleport-plugin-pagerduty
description: A Helm chart for the Teleport Pagerduty Plugin
type: application
version: *version
appVersion: *version
