.version: &version "15.4.0-cloud.1.igs"

apiVersion: v2
name: teleport-plugin-pagerduty
description: A Helm chart for the Teleport Pagerduty Plugin
type: application
version: *version
appVersion: *version
