.version: &version "16.0.2-dev.fred-manifests-0"

apiVersion: v2
name: teleport-plugin-pagerduty
description: A Helm chart for the Teleport Pagerduty Plugin
type: application
version: *version
appVersion: *version
