.version: &version "17.0.0-dev.fred-env-var-migration-1-18"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
