.version: &version "16.1.8-dev-app-servers"

apiVersion: v2
name: teleport-plugin-msteams
description: A Helm chart for the Teleport MsTeams Plugin
type: application
version: *version
appVersion: *version
