.version: &version "17.0.0-dev.fred-manifests-1.2"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
