.version: &version "16.1.0-dev-tross-putty.1"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
