.version: &version "16.4.2-dev-tross-kbd-interactive.2"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
