.version: &version "17.0.0-dev.fred-macos-manifest-1.5"

apiVersion: v2
name: teleport-plugin-email
description: A Helm chart for the Teleport Email Plugin
type: application
version: *version
appVersion: *version
