name: Build buildbox images
on:
  push:
     branches:
       - master
       - branch/**
       - camh/**

jobs:
  build:
    name: Build buildboxes
    runs-on: ubuntu-22.04-32core
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check changes
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          base: ${{ github.ref }}
          filters: |
            buildbox:
              - 'build.assets/versions.mk'
              - 'build.assets/images.mk'
              - 'build.assets/buildbox/Dockerfile'
              - 'build.assets/buildbox/clang-12.sh'
            thirdparty:
              - 'build.assets/images.mk'
              - 'build.assets/buildbox/Dockerfile-thirdparty'
              - 'build.assets/buildbox/build-buildbox.mk'
              - 'build.assets/buildbox/buildbox-common.mk'
              - 'build.assets/buildbox/cross-compile.mk'
              - 'build.assets/buildbox/crosstoolng-configs/**'
              - 'build.assets/buildbox/crosstoolng.mk'
              - 'build.assets/buildbox/pkgconfg/**'
              - 'build.assets/buildbox/thirdparty-libs.mk'

      - name: Set up Docker Buildx
        if: steps.changes.outputs.thirdparty || steps.changes.outputs.buildbox
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          driver: docker

      - name: Login to registry
        if: steps.changes.outputs.thirdparty || steps.changes.outputs.buildbox
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build buildbox-thirdparty
        if: steps.changes.outputs.thirdparty
        run:
          make -C build.assets buildbox-thirdparty PUSH=1

      - name: Build buildbox-ng
        if: steps.changes.outputs.thirdparty || steps.changes.outputs.buildbox
        run:
          make -C build.assets buildbox-ng PUSH=1
