name: Check docs URLs
on:
  pull_request:

jobs:
  changes:
    name: Check for relevant changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
      changed_files: ${{ steps.changes.outputs.changed_files }}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          list-files: csv
          filters: |
            changed:
              - '.github/workflows/doc-urls.yaml'
              - 'lib/**'
              - 'web/**'
              - 'README.md'
              - 'api/**'

  doc-url-test:
    name: Check docs URLs
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out teleport
        uses: actions/checkout@v4
        with:
          repository: 'gravitational/teleport'
          path: teleport

      - name: Generate GitHub Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.REVIEWERS_APP_ID }}
          private-key: ${{ secrets.REVIEWERS_PRIVATE_KEY }}

      - name: Check out shared-workflows
        uses: actions/checkout@v4
        with:
          repository: gravitational/shared-workflows
          path: .github/shared-workflows
          ref: paul.gottschling/2024-11-07-docs-link-check

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

        # Build the bot executable so we can change working directory
      - name: Build the workflow bot
        working-directory: .github/shared-workflows/bot
        run : "go build -o bot"

      - name: Check documentation URLs
        working-directory: teleport
        run: ${{ github.workspace}}/.github/shared-workflows/bot/bot -workflow=docurls -token="${{ steps.generate_token.outputs.token }}" -teleport-path="${{ github.workspace }}/teleport" -reviewers="${{ secrets.reviewers }}"

